### ISSUE TITLE
subtitle text interferes with header images on wide screens

### ISSUE THREAD

**Issue by ngehlenborg** [biovis/2017#1] opened 2016-12-21 20:02 UTC
Text at the top is behind the images (only on wide screens):

![image](https://cloud.githubusercontent.com/assets/1216518/21404270/6b33e880-c78e-11e6-9bb4-b1c65fb41afd.png)

**Comment by amcrisan** [comment] 2016-12-22 23:11
Ok, I know what causes this problem but I don't yet have a good fix. The problem is that the image is treated as part of the background, while the text is a paragraph element in the container that holds that background image. On very wide screens, the background (and image) scales such that it overwrites the paragraph text.  I think this is solvable by making the image an actual image and not part of the background.  I haven't done this yet because  there's also the issue on very large screens of those three green boxes scaling poorly and I want to assess if there is a common solution (so far no).

**Comment by amcrisan** [comment] 2017-01-05 22:18
Should be fixed now.

**Closed as completed by amcrisan** 2017-01-05 22:18 UTC
